package com.cosmic.astrology.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;
import java.util.Map;
/**
 * Comprehensive JWT Response DTO for Vedic Astrology Application
 * Contains authentication token and complete user information
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "JWT Authentication Response with user details")
public class JwtResponse {
    
    // ================ TOKEN INFORMATION ================
    
    @Schema(description = "JWT access token", example = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...")
    private String token;
    
    @Schema(description = "Token type", example = "Bearer", defaultValue = "Bearer")
    private String type = "Bearer";
    
    @Schema(description = "Token expiration time in milliseconds", example = "3600000")
    private Long expiresIn;
    
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @Schema(description = "Token expiration date and time")
    private LocalDateTime expiresAt;
    
    @Schema(description = "Refresh token for extending session")
    private String refreshToken;
    
    // ================ USER INFORMATION ================
    
    @Schema(description = "User's unique username", example = "testuser")
    private String username;
    
    @Schema(description = "User's email address", example = "user@cosmic-astrology.com")
    private String email;
    
    @Schema(description = "User's role in the system", example = "CLIENT")
    private String role;
    
    @Schema(description = "User's first name", example = "John")
    private String firstName;
    
    @Schema(description = "User's last name", example = "Doe")
    private String lastName;
    
    @Schema(description = "User's full name", example = "John Doe")
    @JsonProperty("fullName")
    private String fullName;
    
    @Schema(description = "Whether user's email is verified", example = "true")
    private Boolean emailVerified;
    
    @Schema(description = "User account status", example = "true")
    private Boolean accountEnabled;
    
    // ================ PROFILE INFORMATION ================
    
    @Schema(description = "Profile completion percentage", example = "85")
    private Integer profileCompletionPercentage;
    
    @Schema(description = "Whether user has complete birth data for chart calculations")
    private Boolean hasCompleteBirthData;
    
    @Schema(description = "Whether user has generated their birth chart")
    private Boolean hasGeneratedChart;
    
    @Schema(description = "User's subscription type", example = "PREMIUM")
    private String subscriptionType;
    
    @Schema(description = "Whether user has active subscription")
    private Boolean subscriptionActive;
    
    // ================ ASTROLOGY INFORMATION ================
    
    @Schema(description = "User's Vedic Sun sign", example = "Aries")
    private String sunSign;
    
    @Schema(description = "User's Vedic Moon sign", example = "Cancer")
    private String moonSign;
    
    @Schema(description = "User's Vedic Ascendant/Rising sign", example = "Leo")
    private String risingSign;
    
    @Schema(description = "User's dominant element", example = "Fire")
    private String dominantElement;
    
    @Schema(description = "User's Moon Nakshatra", example = "Rohini")
    private String moonNakshatra;
    
    // ================ USER PREFERENCES ================
    
    @Schema(description = "User's preferred language", example = "en")
    private String preferredLanguage;
    
    @Schema(description = "User's timezone", example = "America/New_York")
    private String timezone;
    
    @Schema(description = "Whether user wants email notifications")
    private Boolean emailNotifications;
    
    @Schema(description = "Whether user wants daily horoscope")
    private Boolean dailyHoroscope;
    
    // ================ STATISTICS ================
    
    @Schema(description = "Number of charts generated by user", example = "5")
    private Integer chartsGenerated;
    
    @Schema(description = "User's current login streak", example = "7")
    private Integer loginStreak;
    
    @Schema(description = "Total number of logins", example = "42")
    private Integer totalLogins;
    
    @Schema(description = "Remaining credits for premium features", example = "10")
    private Integer creditsRemaining;
    
    // ================ SESSION INFORMATION ================
    
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    @Schema(description = "Login timestamp")
    private LocalDateTime loginTime;
    
    @Schema(description = "Client IP address")
    private String clientIp;
    
    @Schema(description = "Device/browser information")
    private String userAgent;
    
    @Schema(description = "Available permissions for this user")
    private List<String> permissions;
    
    @Schema(description = "Available features for this user")
    private List<String> features;
    
    // ================ CONSTRUCTORS ================
    
    public JwtResponse() {
        this.loginTime = LocalDateTime.now();
    }
    
    // Basic constructor (backward compatibility)
    public JwtResponse(String accessToken, String username, String email, String type) {
        this();
        this.token = accessToken;
        this.username = username;
        this.email = email;
        if (type != null) {
            this.type = type;
        }
        this.fullName = username; // Fallback to username
    }
    /**
 * ✅ SOLUTION: Get user information as a Map for frontend consumption
 */
public Map<String, Object> getUser() {
    Map<String, Object> user = new HashMap<>();
    
    // Basic Information
    user.put("id", this.username); // or actual user ID if available
    user.put("username", this.username);
    user.put("email", this.email);
    user.put("role", this.role);
    
    // Personal Information
    user.put("firstName", this.firstName);
    user.put("lastName", this.lastName);
    user.put("fullName", this.fullName);
    user.put("initials", this.getInitials());
    
    // Account Status
    user.put("emailVerified", this.emailVerified);
    user.put("accountEnabled", this.accountEnabled);
    user.put("profileCompletionPercentage", this.profileCompletionPercentage);
    
    // Astrology Information
    user.put("hasCompleteBirthData", this.hasCompleteBirthData);
    user.put("hasGeneratedChart", this.hasGeneratedChart);
    user.put("sunSign", this.sunSign);
    user.put("moonSign", this.moonSign);
    user.put("risingSign", this.risingSign);
    user.put("dominantElement", this.dominantElement);
    user.put("moonNakshatra", this.moonNakshatra);
    
    // Subscription Information
    user.put("subscriptionType", this.subscriptionType);
    user.put("subscriptionActive", this.subscriptionActive);
    user.put("isPremium", this.isPremium());
    
    // Preferences
    user.put("preferredLanguage", this.preferredLanguage);
    user.put("timezone", this.timezone);
    user.put("emailNotifications", this.emailNotifications);
    user.put("dailyHoroscope", this.dailyHoroscope);
    
    // Statistics
    user.put("chartsGenerated", this.chartsGenerated);
    user.put("loginStreak", this.loginStreak);
    user.put("totalLogins", this.totalLogins);
    user.put("creditsRemaining", this.creditsRemaining);
    
    // Status Flags
    user.put("needsProfileCompletion", this.needsProfileCompletion());
    user.put("needsEmailVerification", this.needsEmailVerification());
    user.put("canGenerateChart", this.canGenerateChart());
    
    // Additional Information
    user.put("permissions", this.permissions);
    user.put("features", this.features);
    user.put("welcomeMessage", this.getWelcomeMessage());
    
    return user;
}

    
    // Enhanced constructor for AuthService compatibility
    public JwtResponse(String accessToken, String username, String email, String type, 
                      String role, String firstName, String lastName, Boolean emailVerified) {
        this(accessToken, username, email, type);
        this.role = role;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailVerified = emailVerified;
        this.fullName = buildFullName(firstName, lastName, username);
    }
    
    // Comprehensive constructor
    public JwtResponse(String accessToken, String username, String email, String type,
                      String role, String firstName, String lastName, Boolean emailVerified,
                      Boolean accountEnabled, Integer profileCompletionPercentage,
                      Boolean hasCompleteBirthData, String subscriptionType) {
        this(accessToken, username, email, type, role, firstName, lastName, emailVerified);
        this.accountEnabled = accountEnabled;
        this.profileCompletionPercentage = profileCompletionPercentage;
        this.hasCompleteBirthData = hasCompleteBirthData;
        this.subscriptionType = subscriptionType;
    }
    
    // ================ GETTERS AND SETTERS ================
    
    public String getToken() { return token; }
    public void setToken(String token) { this.token = token; }
    
    public String getType() { return type; }
    public void setType(String type) { this.type = type; }
    
    public Long getExpiresIn() { return expiresIn; }
    public void setExpiresIn(Long expiresIn) { this.expiresIn = expiresIn; }
    
    public LocalDateTime getExpiresAt() { return expiresAt; }
    public void setExpiresAt(LocalDateTime expiresAt) { this.expiresAt = expiresAt; }
    
    public String getRefreshToken() { return refreshToken; }
    public void setRefreshToken(String refreshToken) { this.refreshToken = refreshToken; }
    
    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }
    
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    
    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }
    
    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { 
        this.firstName = firstName; 
        updateFullName();
    }
    
    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { 
        this.lastName = lastName; 
        updateFullName();
    }
    
    public String getFullName() { return fullName; }
    public void setFullName(String fullName) { this.fullName = fullName; }
    
    public Boolean getEmailVerified() { return emailVerified; }
    public void setEmailVerified(Boolean emailVerified) { this.emailVerified = emailVerified; }
    
    public Boolean getAccountEnabled() { return accountEnabled; }
    public void setAccountEnabled(Boolean accountEnabled) { this.accountEnabled = accountEnabled; }
    
    public Integer getProfileCompletionPercentage() { return profileCompletionPercentage; }
    public void setProfileCompletionPercentage(Integer profileCompletionPercentage) { 
        this.profileCompletionPercentage = profileCompletionPercentage; 
    }
    
    public Boolean getHasCompleteBirthData() { return hasCompleteBirthData; }
    public void setHasCompleteBirthData(Boolean hasCompleteBirthData) { 
        this.hasCompleteBirthData = hasCompleteBirthData; 
    }
    
    public Boolean getHasGeneratedChart() { return hasGeneratedChart; }
    public void setHasGeneratedChart(Boolean hasGeneratedChart) { 
        this.hasGeneratedChart = hasGeneratedChart; 
    }
    
    public String getSubscriptionType() { return subscriptionType; }
    public void setSubscriptionType(String subscriptionType) { this.subscriptionType = subscriptionType; }
    
    public Boolean getSubscriptionActive() { return subscriptionActive; }
    public void setSubscriptionActive(Boolean subscriptionActive) { this.subscriptionActive = subscriptionActive; }
    
    public String getSunSign() { return sunSign; }
    public void setSunSign(String sunSign) { this.sunSign = sunSign; }
    
    public String getMoonSign() { return moonSign; }
    public void setMoonSign(String moonSign) { this.moonSign = moonSign; }
    
    public String getRisingSign() { return risingSign; }
    public void setRisingSign(String risingSign) { this.risingSign = risingSign; }
    
    public String getDominantElement() { return dominantElement; }
    public void setDominantElement(String dominantElement) { this.dominantElement = dominantElement; }
    
    public String getMoonNakshatra() { return moonNakshatra; }
    public void setMoonNakshatra(String moonNakshatra) { this.moonNakshatra = moonNakshatra; }
    
    public String getPreferredLanguage() { return preferredLanguage; }
    public void setPreferredLanguage(String preferredLanguage) { this.preferredLanguage = preferredLanguage; }
    
    public String getTimezone() { return timezone; }
    public void setTimezone(String timezone) { this.timezone = timezone; }
    
    public Boolean getEmailNotifications() { return emailNotifications; }
    public void setEmailNotifications(Boolean emailNotifications) { this.emailNotifications = emailNotifications; }
    
    public Boolean getDailyHoroscope() { return dailyHoroscope; }
    public void setDailyHoroscope(Boolean dailyHoroscope) { this.dailyHoroscope = dailyHoroscope; }
    
    public Integer getChartsGenerated() { return chartsGenerated; }
    public void setChartsGenerated(Integer chartsGenerated) { this.chartsGenerated = chartsGenerated; }
    
    public Integer getLoginStreak() { return loginStreak; }
    public void setLoginStreak(Integer loginStreak) { this.loginStreak = loginStreak; }
    
    public Integer getTotalLogins() { return totalLogins; }
    public void setTotalLogins(Integer totalLogins) { this.totalLogins = totalLogins; }
    
    public Integer getCreditsRemaining() { return creditsRemaining; }
    public void setCreditsRemaining(Integer creditsRemaining) { this.creditsRemaining = creditsRemaining; }
    
    public LocalDateTime getLoginTime() { return loginTime; }
    public void setLoginTime(LocalDateTime loginTime) { this.loginTime = loginTime; }
    
    public String getClientIp() { return clientIp; }
    public void setClientIp(String clientIp) { this.clientIp = clientIp; }
    
    public String getUserAgent() { return userAgent; }
    public void setUserAgent(String userAgent) { this.userAgent = userAgent; }
    
    public List<String> getPermissions() { return permissions; }
    public void setPermissions(List<String> permissions) { this.permissions = permissions; }
    
    public List<String> getFeatures() { return features; }
    public void setFeatures(List<String> features) { this.features = features; }
    
    // ================ UTILITY METHODS ================
    
    /**
     * Build full name from first and last name
     */
    private String buildFullName(String firstName, String lastName, String fallback) {
        if (firstName == null && lastName == null) {
            return fallback != null ? fallback : "User";
        }
        if (firstName == null) {
            return lastName;
        }
        if (lastName == null) {
            return firstName;
        }
        return firstName + " " + lastName;
    }
    
    /**
     * Update full name when first or last name changes
     */
    private void updateFullName() {
        this.fullName = buildFullName(this.firstName, this.lastName, this.username);
    }
    
    /**
     * Get user initials
     */
    @JsonProperty("initials")
    public String getInitials() {
        StringBuilder initials = new StringBuilder();
        if (firstName != null && !firstName.isEmpty()) {
            initials.append(firstName.charAt(0));
        }
        if (lastName != null && !lastName.isEmpty()) {
            initials.append(lastName.charAt(0));
        }
        if (initials.length() == 0 && username != null && !username.isEmpty()) {
            initials.append(username.charAt(0));
        }
        return initials.toString().toUpperCase();
    }
    
    /**
     * Check if user is a premium user
     */
    @JsonProperty("isPremium")
    public boolean isPremium() {
        return subscriptionType != null && 
               (subscriptionType.equals("PREMIUM") || subscriptionType.equals("PROFESSIONAL")) &&
               Boolean.TRUE.equals(subscriptionActive);
    }
    
    /**
     * Check if user needs to complete profile
     */
    @JsonProperty("needsProfileCompletion")
    public boolean needsProfileCompletion() {
        return profileCompletionPercentage == null || profileCompletionPercentage < 80;
    }
    
    /**
     * Check if user needs to verify email
     */
    @JsonProperty("needsEmailVerification")
    public boolean needsEmailVerification() {
        return !Boolean.TRUE.equals(emailVerified);
    }
    
    /**
     * Check if user can generate birth chart
     */
    @JsonProperty("canGenerateChart")
    public boolean canGenerateChart() {
        return Boolean.TRUE.equals(hasCompleteBirthData) && Boolean.TRUE.equals(accountEnabled);
    }
    
    /**
     * Get welcome message based on user data
     */
    @JsonProperty("welcomeMessage")
    public String getWelcomeMessage() {
        String name = fullName != null ? fullName : username;
        String timeOfDay = getTimeOfDayGreeting();
        
        if (Boolean.TRUE.equals(hasGeneratedChart)) {
            return String.format("%s %s! Welcome back to your cosmic journey.", timeOfDay, name);
        } else if (Boolean.TRUE.equals(hasCompleteBirthData)) {
            return String.format("%s %s! Ready to explore your Vedic birth chart?", timeOfDay, name);
        } else {
            return String.format("%s %s! Complete your birth profile to unlock personalized insights.", timeOfDay, name);
        }
    }
    
    private String getTimeOfDayGreeting() {
        int hour = LocalDateTime.now().getHour();
        if (hour < 6) return "🌅 Good morning";
        if (hour < 12) return "🌞 Good morning";
        if (hour < 17) return "🌤️ Good afternoon";
        if (hour < 21) return "🌅 Good evening";
        return "🌙 Good night";
    }
    
    /**
     * Get authentication header value
     */
    public String getAuthorizationHeader() {
        return type + " " + token;
    }
    
    /**
     * Check if token is expired (requires expiresAt to be set)
     */
    public boolean isExpired() {
        return expiresAt != null && LocalDateTime.now().isAfter(expiresAt);
    }
    
    /**
     * Get remaining time until token expires (in minutes)
     */
    public long getMinutesUntilExpiry() {
        if (expiresAt == null) return -1;
        return java.time.temporal.ChronoUnit.MINUTES.between(LocalDateTime.now(), expiresAt);
    }
    
    // ================ BUILDER PATTERN SUPPORT ================
    
    /**
     * Builder for creating JwtResponse with fluent API
     */
    public static class Builder {
        private final JwtResponse response = new JwtResponse();
        
        public Builder token(String token) {
            response.setToken(token);
            return this;
        }
        
        public Builder type(String type) {
            response.setType(type);
            return this;
        }
        
        public Builder username(String username) {
            response.setUsername(username);
            return this;
        }
        
        public Builder email(String email) {
            response.setEmail(email);
            return this;
        }
        
        public Builder role(String role) {
            response.setRole(role);
            return this;
        }
        
        public Builder firstName(String firstName) {
            response.setFirstName(firstName);
            return this;
        }
        
        public Builder lastName(String lastName) {
            response.setLastName(lastName);
            return this;
        }
        
        public Builder emailVerified(Boolean emailVerified) {
            response.setEmailVerified(emailVerified);
            return this;
        }
        
        public Builder expiresIn(Long expiresIn) {
            response.setExpiresIn(expiresIn);
            if (expiresIn != null) {
                response.setExpiresAt(LocalDateTime.now().plusSeconds(expiresIn / 1000));
            }
            return this;
        }
        
        public Builder astrologySigns(String sunSign, String moonSign, String risingSign) {
            response.setSunSign(sunSign);
            response.setMoonSign(moonSign);
            response.setRisingSign(risingSign);
            return this;
        }
        
        public JwtResponse build() {
            response.updateFullName();
            return response;
        }
    }
    
    public static Builder builder() {
        return new Builder();
    }
    
    // ================ OBJECT METHODS ================
    
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        
        JwtResponse that = (JwtResponse) obj;
        return Objects.equals(token, that.token) &&
               Objects.equals(username, that.username) &&
               Objects.equals(email, that.email);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(token, username, email);
    }
    
    @Override
    public String toString() {
        return String.format("JwtResponse{username='%s', email='%s', role='%s', type='%s', emailVerified=%s}",
                           username, email, role, type, emailVerified);
    }
}
